# Generated by Django 2.0.2 on 2018-05-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertechinfo',
            name='is_log',
            field=models.BooleanField(default=False),
        ),
    ]
