# Generated by Django 2.0.2 on 2018-05-11 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_messaging', '0002_usertechinfo_is_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertechinfo',
            name='is_log',
        ),
    ]
