# Generated by Django 2.0.2 on 2018-06-05 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drf_messaging', '0003_remove_usertechinfo_is_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(blank=True, max_length=2000, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drf_messaging.Messages')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
