# Generated by Django 2.0.2 on 2018-06-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_messaging', '0004_reportedmessages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
